### ISSUE TITLE
Ignore flaky Nsili testMultipleTarCompressOrder unit test

### ISSUE THREAD

**Issue by shaundmorris** [codice/alliance#767]
https://github.com/codice/alliance/blob/master/catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/requests/OrderRequestImplTest.java#L380

This test is occasionally failing on builds.

```
[2019-11-12T04:04:40.367Z] [ERROR] testMultipleTarCompressOrder(org.codice.alliance.nsili.endpoint.requests.OrderRequestImplTest)  Time elapsed: 0.013 s  <<< ERROR!
4:36:58  Unfinished stubbing detected here:
14:36:58  -> at org.codice.alliance.nsili.endpoint.requests.OrderRequestImplTest.setupMocks(OrderRequestImplTest.java:99)
14:36:58  
14:36:58  E.g. thenReturn() may be missing.
14:36:58  Examples of correct stubbing:
14:36:58      when(mock.isOk()).thenReturn(true);
14:36:58      when(mock.isOk()).thenThrow(exception);
14:36:58      doThrow(exception).when(mock).someVoidMethod();
14:36:58  Hints:
14:36:58   1. missing thenReturn()
14:36:58   2. you are trying to stub a final method, you naughty developer!
14:36:58   3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed
14:36:58  
14:36:58  	at org.codice.alliance.nsili.endpoint.requests.OrderRequestImplTest.setupMocks(OrderRequestImplTest.java:99)
14:36:58  	at org.codice.alliance.nsili.endpoint.requests.OrderRequestImplTest.setUp(OrderRequestImplTest.java:90)
14:36:58  
14:36:58  [INFO] Running org.codice.alliance.nsili.endpoint.CreationMgrImplTest
14:36:58  [INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 s - in org.codice.alliance.nsili.endpoint.CreationMgrImplTest
14:36:58  [INFO] Running org.codice.alliance.nsili.endpoint.AccessManagerImplTest
14:36:58  [INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.063 s - in org.codice.alliance.nsili.endpoint.AccessManagerImplTest
14:36:58  [INFO] Running org.codice.alliance.nsili.endpoint.GetRelatedFilesRequestImplTest
14:36:58  [INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.466 s - in org.codice.alliance.nsili.endpoint.GetRelatedFilesRequestImplTest
14:36:58  [INFO] Running org.codice.alliance.nsili.endpoint.NsiliLibraryImplTest
14:36:58  [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in org.codice.alliance.nsili.endpoint.NsiliLibraryImplTest
14:36:59  Exception in thread "Thread-31" java.lang.NullPointerException
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.getData(SubmitStandingQueryRequestImpl.java:577)
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.run(SubmitStandingQueryRequestImpl.java:491)
14:36:59  Exception in thread "Thread-56" java.lang.NullPointerException
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.getData(SubmitStandingQueryRequestImpl.java:577)
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.run(SubmitStandingQueryRequestImpl.java:491)
14:36:59  Exception in thread "Thread-54" java.lang.NullPointerException
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.getData(SubmitStandingQueryRequestImpl.java:577)
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.run(SubmitStandingQueryRequestImpl.java:491)
14:36:59  Exception in thread "Thread-64" java.lang.NullPointerException
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.getData(SubmitStandingQueryRequestImpl.java:577)
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.run(SubmitStandingQueryRequestImpl.java:491)
14:36:59  Exception in thread "Thread-47" java.lang.NullPointerException
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.getData(SubmitStandingQueryRequestImpl.java:577)
14:36:59  	at org.codice.alliance.nsili.endpoint.requests.SubmitStandingQueryRequestImpl$ExecutionThread.run(SubmitStandingQueryRequestImpl.java:491)
14:36:59  [INFO] 
14:36:59  [INFO] Results:
14:36:59  [INFO] 
[2019-11-18T21:36:59.375Z] [ERROR] Errors: 
[2019-11-18T21:36:59.375Z] [ERROR]   OrderRequestImplTest.setUp:90->setupMocks:99 UnfinishedStubbing 
```

**Comment by shaundmorris** [comment]
We ignored one test but the unit tests in the class are proving to be flakey. So something more drastic will be needed. Closing this issue.
